Azureに移行＆pm2の導入
wagumi/wagumi-members-db-updater pull request #3
Opened 2023-06-03 07:52 UTC by gamoyan

### 概要
現在ローカルで手動実行しているDB更新について、gitaction経由でrsyncして同期
pm2にてCronによる定期実行するように修正

### 処理概要
1.rsyncは以下を参考
https://github.com/wagumi/wagumi-sbt-discord-bot/blob/main/.github/workflows/main.yaml
2.ssh接続してnpmインストール＆pm2実行
課題：sshでAzureのUbuntuコンテナに入った後にgitActionのタスクランナーから入ると
シェル変数がうまく使用できないため、２回目以降のコミットは②のコマンドとするべきであるが、
ハンドリングができていない。２回目以降に②の修正と変更する対応で検討しています。
定期実行はUTC　0:00
①`pm2 start main.js --cron-restart="10 0 * * *”`
②`pm2 restart main.js --cron-restart="10 0 * * *”`

2023-06-05 18:20 UTC, tksohishi requested changes

2023-06-05 18:20 UTC, tksohishi commented on .github/config.yaml
> +          npm install
`node_modules` はline 17あたりで作ってrsyncでsyncしているのでこちらでは必要なさそうです

2023-06-05 18:20 UTC, tksohishi commented on .github/config.yaml
> +      - name: ssh connert and pm2 run
こちら用意していただいてありがとうございます！このレポジトリは一旦動かし始めたらそこまで変更の必要はなさそうなので実際にpm2で動かすのは直接sshでつないでやってしまおうと思っていました。

2023-06-07 12:03 UTC, gamoyan commented on .github/config.yaml
> +      - name: ssh connert and pm2 run
承知しました！
そうしましたら32行目以下は不要になるので削除しますね。

2023-06-07 12:03 UTC, gamoyan commented on .github/config.yaml
> +          npm install
ありがとうございます！以下の対応にて削除します。
https://github.com/wagumi/wagumi-members-db-updater/pull/3/files#r1221465706

2023-06-07 12:07 UTC, gamoyan commented on .github/config.yaml
> +          npm install
修正しました。
e9ea4edd8d27b59cff9d03bf6cd736f9db0ad375

2023-06-09 02:40 UTC, tksohishi commented on .github/config.yaml
> +    types: [closed]
これだとmergeされなくてもPRがcloseしたらdeployされる?他のレポで使っている以下の設定だと問題ありますか？
```
on:
  push:
    branches:
      - main
```

2023-06-09 02:41 UTC, tksohishi commented on .github/config.yaml
> +        run: npm install
`npm ci` がいいかもしれませんね

2023-06-10 14:29 UTC, gamoyan commented on .github/config.yaml
> +    types: [closed]
問題ないかと思います。強いてあげるならpullrequest介さず、mainをpushしてもGitActionが動く位ですね。
こちら上記の通り修正します。

2023-06-10 15:22 UTC, tksohishi commented on .github/config.yaml
> +    types: [closed]
その場合も動いてほしいので問題ないはずです。mainにあるものがdeployされているという状態にしたいです。

2023-06-10 15:37 UTC, gamoyan commented on .github/config.yaml
> +    types: [closed]
>その場合も動いてほしいので問題ないはずです。mainにあるものがdeployされているという状態にしたいです。
承知しました。こちらご指摘の通り修正しました。
https://github.com/wagumi/wagumi-members-db-updater/pull/3/commits/ee1c9b91ba05e51290cb610dbfc2e7001dc35489

2023-06-10 15:39 UTC, gamoyan commented on .github/config.yaml
> +        run: npm install
此方修正しました。
https://github.com/wagumi/wagumi-members-db-updater/pull/3/commits/e31da466423145c9bf85f08d050638740d315783

2023-06-11 01:07 UTC, tksohishi approved these changes
LGTMです！タイミングを見てmerge->deployしてみましょう 👌🏼

2023-06-12 13:17 UTC, merged